name: WildernessTP-Original
main: me.Lme999.WildernessTeleport.Main
version: 0.0.1-DEV
description: A plugin to teleport you to a random area in the wilderness.
authors: [Lme999,Rufust,FletchXYZ]

commands:
  wildernessteleport:
    aliases: [wtp, wildernesstp, wilderness, wild]
    description: Teleport to Wilderness
    usage: /<command> [set|reload|help]
