name: WildernessTP-Original
main: me.Lme999.WildernessTeleport.Main
version: 0.0.1
description: A plugin to teleport you to a random area in the wilderness.
authors: [Lme999,Rufust]

commands:
  wildernessteleport:
    aliases: [wtp, wildernesstp, wilderness, wild]
    description: Teleport to wilderness
