name: WildernessTeleport
version: 0.0.1
authors: [Lme999,FletchTech90]
main: me.Lme999.WildernessTeleport.Main

commands:
    wildernessteleport:
        description: WildernessTP
        aliases: [wild,wtp,wildernesstp,wilderness]

permissions:
    wilderness.help:
        default: op